### Register a new user
POST http://localhost:8000/api/register/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}



### Obtain token
POST http://localhost:8000/api/login/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### Obtain token
POST http://localhost:8000/api/login/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### Get item list
GET http://localhost:8000/api/items/
Authorization: Bearer 364c47a7e21f12f66908802160c6c8b62b5f5116

